builds:
  - binary: tmp
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: tmp
    homepage: https://github.com/hamza-007/tmp
    tap:
      owner: hamza abdellaoui
      name: tmp
    commit_author:
      name: hamza-007
      email: hamzaabdellaoui26648999@gmail.com

checksum:
  name_template: 'checksums.txt'