version: '3.8'

volumes:
  database-volume:

services:
  db:
    image: timescale/timescaledb:2.5.2-pg14-oss
    container_name: movies-Database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - database-volume:/var/lib/postgresql/data/
    ports: 
      - ${POSTGRES_PORT}:5432