CREATE EXTENSION IF NOT EXISTS "citext" CASCADE;
CREATE EXTENSION IF NOT EXISTS "ltree" CASCADE;
CREATE EXTENSION IF NOT EXISTS "btree_gist" CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE;
CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch" CASCADE;
CREATE EXTENSION IF NOT EXISTS "pg_trgm" CASCADE;
CREATE EXTENSION IF NOT EXISTS "timescaledb" CASCADE;